version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook:
    build:
      context: .
      target: storybook
    ports:
      - "6006:80"
    restart: unless-stopped

  dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development